### PR TITLE
use local paths and remove trailing spaces

### PR DESCRIPTION
**Pull request by matu3ba**
reason: only including tau.h fails

### CODE REVIEW

**Comment by jasmcaus** [comment]
There's a reason why the `<tau/...>` syntax exists. If you prefer using the `"..."` approach, you'll need to make a small change in the include paths in CMakeLists.txt. I'm happy to merge the spacing changes, but not going to  atm with the include path changes

**Comment by matu3ba** [comment]
> There's a reason why the <tau/...> syntax exists.

So you want users of tau to either use CMake or `-Ltau` ?
The `Ltau` option is not explained in the README.

**Comment by jasmcaus** [comment]
Primarily CMake. Tau is really meant to be used alongside a CMake-built project. Haven't explored the `-LTau` option like you mentioned since I primarily use CMake. But, I guess it's worth exploring as well.

**Comment by matu3ba** [comment]
Pardon, it was `Itau` to include headers:
```txt
-I <dir>                Add directory to the end of the list of include search paths
```

**Pull request closed without merging**
